-- MySQL Script generated by MySQL Workbench
-- dom 11 abr 2021 17:31:27 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SocialReading
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocialReading` DEFAULT CHARACTER SET utf8 ;
USE `SocialReading` ;

-- -----------------------------------------------------
-- Table `SocialReading`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialReading`.`book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `author` VARCHAR(50) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `isbn` CHAR(13) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  UNIQUE INDEX `isbn` (`isbn` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SocialReading`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialReading`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `age` INT(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SocialReading`.`is_friend_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialReading`.`is_friend_of` (
  `id_user_a` INT(11) NOT NULL,
  `id_user_b` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_a`, `id_user_b`),
  INDEX `id_user_b` (`id_user_b` ASC),
  CONSTRAINT `is_friend_of_ibfk_1`
    FOREIGN KEY (`id_user_a`)
    REFERENCES `SocialReading`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `is_friend_of_ibfk_2`
    FOREIGN KEY (`id_user_b`)
    REFERENCES `SocialReading`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SocialReading`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialReading`.`reading` (
  `id_user` INT(11) NOT NULL,
  `id_book` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `qualification` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `id_book`),
  INDEX `id_book` (`id_book` ASC),
  CONSTRAINT `reading_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `SocialReading`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reading_ibfk_2`
    FOREIGN KEY (`id_book`)
    REFERENCES `SocialReading`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
